[project]
name = "vertice-backend"
version = "0.1.0"
description = "Análisis de sesgos de género en letras de canciones en español"
requires-python = ">=3.11"

dependencies = [
    "fastapi>=0.111.0",
    "uvicorn>=0.30.0",
    "python-dotenv>=1.0.0",
    "pandas>=2.2.0",
    "requests>=2.32.0",
    "lyricsgenius>=3.0.1",
    "supabase>=2.28.0",
    "beautifulsoup4>=4.14.3",
    "spotipy>=2.25.2",
    "groq>=1.0.0",
    "isodate>=0.7.2",
    "google-genai>=1.66.0",
    "python-levenshtein>=0.27.3",
    "musicbrainzngs>=0.7.1",
    "langdetect>=1.0.9",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.4.0",
]
