[project]
name = "vertice-backend"
version = "0.1.0"
description = "Análisis de sesgos de género en letras de canciones en español"
requires-python = ">=3.11"

dependencies = [
    "fastapi>=0.111.0",
    "uvicorn>=0.30.0",
    "python-dotenv>=1.0.0",
    "pandas>=2.2.0",
    "requests>=2.32.0",
    "lyricsgenius>=3.0.1",
    "httpx>=0.28.1",
    "pydantic>=2.12.5",
    "groq>=1.1.1",
    "python-multipart>=0.0.22",
    "supabase>=2.28.0",
    "beautifulsoup4>=4.14.3",
    "spotipy>=2.25.2",
    "groq>=1.0.0",
    "isodate>=0.7.2",
    "google-genai>=1.66.0",
    "python-levenshtein>=0.27.3",
    "musicbrainzngs>=0.7.1",
    "langdetect>=1.0.9",
    "langchain-core>=1.2.18",
    "langchain-google-genai>=4.2.1",
    "langchain-ollama>=1.0.1",
    "langsmith>=0.7.16",
    "langgraph>=1.1.0",
    "scipy>=1.17.1",
    "langgraph-cli[inmem]>=0.4.15",
    "openai>=2.26.0",
    "typing-extensions>=4.15.0",
    "langchain-community>=0.4.1",
    "langchain>=1.2.13",
    "langfuse<3.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.4.0",
]

[tool.pytest.ini_options]
testpaths = ["app/tests"]   
pythonpath = ["."] 
addopts = "-v" 
