name: Deploy

on:
  push:
    branches: [main]

jobs:
  # Solo despliega en push a main
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend a Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}"

      - name: Deploy frontend a Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}"