name: Deploy

on:
  push:
    branches: [main]

jobs:
  # Primero corre el CI completo
  ci:
    uses: ./.github/workflows/ci.yml  
    secrets: inherit                    

  # Solo despliega si el CI pasa
  deploy:
    runs-on: ubuntu-latest
    needs: [ci]                         
    steps:
      - name: Deploy backend a Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}"

      - name: Deploy frontend a Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}"